name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo ${{secrets.USERNAME}}

      - name: Run a multi-line script
        run: |
          echo ${{secrets.PASSWORD}}
          echo test, and deploy your project.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Prepare deploy"
        run: echo "Working heavy!"
